In [1]:
import numpy as np
import imageio as img

In [2]:
def extractPixels(imgLocation):
    pixelMatrix = img.imread(imgLocation)
    return pixelMatrix

In [3]:
#Extracting Pixels Data from the image
imgLoc = "abc.jpeg"
pixelsMatrix = extractPixels(imgLoc)
pixelsMatrix = np.array(pixelsMatrix)
height = len(pixelsMatrix)
width = len(pixelsMatrix[0])
#Some Info
#It will have 284 rows and 645 columns (each pixel will be represented by a RGB row vector)
#4d matrix 

# print(pixels[100][200][1])
# print(len(pixels))


#Test Experiment for eigenvalues and eigenvectors
# matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
# type(matrix)
# eigValues, eigVectors = np.linalg.eig(matrix)
# print("Eigenvalues: \n", eigValues)
# print("Eigenvectors: \n", eigVectors)

# 
print(np.array([pixelsMatrix[0][0]]))
print("Initiated : Conversion to Data Matrix")
pixelData = np.empty((0,3),int)
for i in range(height):
    for j in range(width):
        pixelData = np.concatenate((pixelData, np.array([pixelsMatrix[i][j]])), axis = 0)
        #print(i,j)
print("Completed : Conversion to Data Matrix")


[[233 233 231]]
Initiated : Conversion to Data Matrix
Completed : Conversion to Data Matrix


In [15]:
def pca(matrix, components):
    print(len(matrix), len(matrix[0]))
    meaned_matrix = matrix - np.mean(matrix, axis=0)
    cov_matrix = np.cov(meaned_matrix, rowvar=False)
    eig_values, eig_vectors = np.linalg.eigh(cov_matrix)
    
    sortedIndices = np.argsort(eig_values)[::-1]
    sorted_eig_values = eig_values[sortedIndices]
    sorted_eig_vectors = eig_vectors[:,sortedIndices]
    
    eig_vectors_taken = sorted_eig_vectors[:,0:components]
    
    Y = np.dot(eig_vectors_taken.transpose(), meaned_matrix.transpose()).transpose()
    
    return Y

In [26]:
reduced_pixels = pca(pixelData, 3)
print(len(reduced_pixels), len(reduced_pixels[0]))
print(reduced_pixels)

183180 3
183180 3
[[ -90.40089017    3.28550028    6.64852795]
 [ -91.88177973    2.69048719    8.50673287]
 [ -93.04529496    1.10387082    8.14773313]
 ...
 [-129.37574542    5.18093776    2.02597729]
 [-129.37574542    5.18093776    2.02597729]
 [-129.37574542    5.18093776    2.02597729]]


In [27]:
img.imsave("xyz.jpeg", reduced_pixels)

Lossy conversion from float64 to uint8. Range [-129.37574542103098, 285.8296035961857]. Convert image to uint8 prior to saving to suppress this warning.


OSError: encoder error -2 when writing image file